services:
  database:
    container_name: db
    image: mysql:9.0
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user-password
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - data:/var/lib/mysql

  api:
    container_name: api
    depends_on:
      database:
        condition: service_healthy
    build: 
      context: WebAPI
      dockerfile: Dockerfile
    environment:
      DB_HOSTNAME: db
      DB_NAME: testdb
      DB_USER: user
      DB_PASSWORD: user-password
    ports:
      - "8080:8080"
      - "8081:8081"
volumes:
  data: