// <auto-generated />
using System;
using Correction01Personnage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Correction01Personnage.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250204111256_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Correction01Personnage.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Armor")
                        .HasColumnType("int")
                        .HasColumnName("armor");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("creation_date");

                    b.Property<int>("Damages")
                        .HasColumnType("int")
                        .HasColumnName("damages");

                    b.Property<int>("HeathPoints")
                        .HasColumnType("int")
                        .HasColumnName("heath_points");

                    b.Property<int>("Kills")
                        .HasColumnType("int")
                        .HasColumnName("kills");

                    b.Property<int>("MaxHeathPoints")
                        .HasColumnType("int")
                        .HasColumnName("max_heath_points");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("pseudo");

                    b.HasKey("Id");

                    b.ToTable("character");
                });
#pragma warning restore 612, 618
        }
    }
}
